document.body.style.backgroundColor = "yellow";
let jsP = document.createElement("p");
jsP.textContent = "Hello World!";
document.body.appendChild(jsP)

for (let i = 0; i < 100; i++) {
  let jsH1 = document.createElement("h1");
  jsH1.textContent = "Hey I was generated by js";
  document.body.appendChild(jsH1);
  jsH1.style.color = "blue";
}

// document.body.removeChild(jsP)

jsP.style.fontSize = "100px"



let exsistingH1s = document.getElementsByTagName("h1")
exsistingH1s[0].style.color = "green"
exsistingH1s[1].style.color = "red"

let jsSpan = document.getElementById("spanId")
jsSpan.style.color = "purple"
jsSpan.textContent = "I am a span"
jsSpan.style.fontSize = "100px"
jsSpan.style.textDecoration = "underline"


// let ourSpan = document.getElementsByName("ourSpan");
// ourSpan[0].style.color = "green";
// ourSpan[1].style.color = "red";

// let ourSpan = document.getElementsByName("ourSpan");
// ourSpan[0].style.color = "green";
// ourSpan[1].style.color = "red";

let squareDiv = document.getElementsByClassName("square-box")
squareDiv[0].innerHTML = "Hello I am a <b> box </b>"

let niceSpanWithId = document.querySelector("#spanId")
niceSpanWithId.style.backgroundColor = "purple"

let divWithClass = document.querySelector(".square-box");
divWithClass.style.backgroundColor = "black"
divWithClass.style.color = "white"

let span = document.querySelectorAll("Span");
span[0].style.color = "red";
span[1].style.color = "yellow";

